### ISSUE TITLE
The server does not support version 7.4 of the PHP Project specification

### ISSUE THREAD

**Issue by ibakirov** [eclipse/pdt#112]
**Describe the bug**
Unable to run PHP scripts with PHP 7.4.21 engine version under Eclipse without downgrading projects validation version to 7.3

**Describe the eclipse environment**
 - Eclipse: Version: 2021-06 (4.20.0)
 - Build id: 20210612-2011

**Describe your system**
 - OS: Windows 10 Pro x64 ENG
 - PHP Version: 7.4.21 x64 and x86 version tested

**To Reproduce**
1. Go to 'New PHP project'
2. Give project name
3. Select PHP version 7.4
4. Create simple index.php file:
`phpinfo();`
5. Select index.php file, right click and select Run on server and select PHP built-in server
6. Server's host name: localhost
7. Server name: PHP Built-in Server at localhost
8. Server runtime environment select and add path to PHP 7.4.21 executable
9. Get error: The server does not support version 7.4 of the PHP Project specification
10. Workaround: Downgrade PHP project PHP version to 7.3 and below

**Expected behavior**
PHP project with 7.4 PHP support must run on PHP 7.4.21 engine.

**Screenshots**
Project with PHP 7.4 version:
![Eclipse-php-error](https://user-images.githubusercontent.com/7983476/125606377-dd2371bb-78fc-4dc2-895b-4c4a62bb964c.png)

Project with PHP 7.3 version:
![Eclipse-php-success](https://user-images.githubusercontent.com/7983476/125606380-2eafe344-60a5-49a7-8700-b44778c585cc.png)

**Comment by agmckee** [comment]
Dawid fixed this in a PR but that fix was not included in the 7.2 release.

**Comment by agmckee** [comment]
I believe this issue can be closed - the aforementioned fix was released in PDT 7.2.1. @ibakirov, perhaps you can confirm and close this issue if it is now working properly.

**Comment by ibakirov** [comment]
@agmckee today checked on *Eclipse IDE for PHP Developers* and there is no issues anymore. Checked with PHP 7.4.27 and 8.0.10 version.

_Eclipse PDT version:_
`Version: 2021-12 (4.22.0)
Build id: 20211202-1639
`

**Comment by ibakirov** [comment]
xdfr
