### ISSUE TITLE
Line numbers garbled on Wayland

### ISSUE THREAD

**Issue by o-alquimista** [eclipse/pdt#113]
**Describe the bug**
The vertical line number region sporadically exhibits garbled or duplicated text.
It is reproducible with both PHP and JavaScript files.

**Describe the eclipse environment**
This is only reproducible on Wayland sessions. I have tested it on Ubuntu 21.04 and Fedora Workstation 34 using the GNOME desktop.

Eclipse 2021-06
PDT 7.2.0

**Describe your system**
 - PHP Version: 7.4

**To Reproduce**
1. Open a file that is long enough to scroll through it
2. Keep scrolling up and down (with the mouse wheel or touchpad) until the line numbers become garbled. Scrolling any further from that point might trigger a new render that eliminates the glitch.

**Screenshots**
![Captura de tela de 2021-08-16 12-48-17](https://user-images.githubusercontent.com/25424263/129598857-f38999e5-48ab-42ec-b2a0-889fbc651691.png)
![Captura de tela de 2021-08-16 12-48-26](https://user-images.githubusercontent.com/25424263/129598860-a32612cd-656b-4ea7-b1ac-a8967876d62e.png)

**Comment by rimace** [comment]
Is it really specific to Eclipse PDT?
This seems more like a general problem of Eclipse.

**Comment by o-alquimista** [comment]
> Is it really specific to Eclipse PDT?
> This seems more like a general problem of Eclipse.

Which Eclipse editor should I try to confirm this?

**Comment by pounard** [comment]
> Which Eclipse editor should I try to confirm this?

Any one, which is not the PHP editor.

**Comment by o-alquimista** [comment]
Yeah, it's not just PDT.

![Captura de tela de 2021-08-23 09-36-39](https://user-images.githubusercontent.com/25424263/130448217-8b9011dc-d951-4c5c-bf26-8bd2b2ab3d3e.png)

**Comment by rimace** [comment]
Eclipse itself: Platform/Workbench.
That is the bug tracker for the "base" Eclipse IDE Software.

**Comment by o-alquimista** [comment]
Done: https://bugs.eclipse.org/bugs/show_bug.cgi?id=575574

I guess this can be closed now.

**Comment by enexusde** [comment]
I updated today to 
### Ubuntu 23.10 
(Linux main 6.5.0-10-generic #10-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 13 13:49:38 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux) 

And the bug is **gone**.
