### ISSUE TITLE
teach linter the meaning of the $_ variable

### ISSUE THREAD

**Issue by divinity76** [eclipse/pdt#119]
**Is your feature request related to a problem? Please describe.**
the linter doesn't understand the meaning of the $_ variable

**Is this feature require new UI elements or modify existing?**
no

**Describe the solution you'd like**
teach the linter that the $_ variable means "a variable that have to exist for some reason, but isn't being used"

**Describe alternatives you've considered**
N/A

**Additional context**
in both the php internals mailing list and in RFC's, $_ is the variable name used when a variable have to exist for some reason, but isn't being used. a common example is iterating keys with foreach, 
```php
foreach(returns_array() as $key => $_){
    (...)
}
```
here $_ have to exist as demanded by the foreach api, but it's not being used. pdt linter will complain that $_ isn't being used here...
examples in the wild: 
- (foreach) https://wiki.php.net/rfc/is_list
- (foreach) https://wiki.php.net/rfc/restrict_globals_usage
- (unused argument) https://wiki.php.net/rfc/uuid
- https://marc.info/?l=php-internals&m=160022450030432&w=2
(i know there's more examples though)

 can we teach the linter that the specific variable name $_ means the variable don't have to be used? eg teach the linter not to give the specific complaint

> Variable '$_' is never used

**Comment by mlocati** [comment]
It's applicable in other cases too.

Let's assume we have two PHP files, `a.php` and `b.php`.
`a.php` defined a variable, then it includes `b.php`, which uses that variable.
In `b.php` we can tell the linter that the variable is defined with the `@var` php doc, but there's no way (and no official phpdoc API afaik) to tell the linter that the variable will be actually used.

Example:

- `a.php`
   ```php
   <?php
   $foo = 'bar';
   // Here we'd need a phpdoc to tell the linter that $foo is actually used
   
   include 'b.php';
   ```

- `b.php`
   ```php
   <?php
   /** @var string $foo */
   echo $foo;
   ```

PS: @divinity76 The subject of this issue is not very meaningful: `$_` is just the name of the variable in your specific use case. Could you change it to something more generic?

**Comment by divinity76** [comment]
@mlocati 
>but there's no way (and no official phpdoc API afaik) to tell the linter that the variable will be actually used.

hmm, turns out that if you declare the variable with phpdoc before using it, then it seems the linter won't complain, eg
```
<?php
/** @var string $foo */
$foo = 'bar';
// Here we'd need a phpdoc to tell the linter that $foo is actually used

include 'b.php';
```
is ok (the linter does not complain about it not being used..), but
```
<?php
$foo = 'bar';
/** @var string $foo */
// Here we'd need a phpdoc to tell the linter that $foo is actually used

include 'b.php';
```
is not ok and makes the linter complain  that $foo isn't being used
 ¯\\\_(ツ)\_\/¯

>$_ is just the name of the variable in your specific use case

well it's slightly more than that, it's \*the\* variable name used for "unused variables that have to exist" in PHP RFC's and mailing lists, see for example
- (foreach) https://wiki.php.net/rfc/is_list
- (foreach) https://wiki.php.net/rfc/restrict_globals_usage 
- (unused argument) https://wiki.php.net/rfc/uuid
- https://marc.info/?l=php-internals&m=160022450030432&w=2

(huh, finding examples was harder than i thought, i know there's more though)

> Could you change it to something more generic?

i'm open to suggestions
