### ISSUE TITLE
codeassist erroneously thinks Throwable::getMessage() returns void. it returns string

### ISSUE THREAD

**Issue by divinity76** [eclipse/pdt#125]
**Describe the bug**
codeassist erroneously thinks Throwable::getMessage() returns void. it returns string

**Describe the eclipse environment**
Eclipse Version: 2021-09 (4.21.0)
Build id: 20210910-1417
PDT version 7.2.0.202005271851

**Describe your system**
 - OS: Xubuntu Linux 20.04
 - Version (?? do you mean Eclipse version or OS version? 20.04 kernel 5.4.0-88-generic x86_64)
 
**To Reproduce**
1: open a php file and write
```php
<?php (new Throwable())->getMessage();
```
then go to the M and press ctrl+shift+space

**Expected behavior**
code assist should inform us that getMessage() returns string. instead it says void.

**Screenshots**

**Additional context**

just checked the code generating the typehints, and my first thought was https://stackoverflow.com/a/1732454/1067003
- ideally that code should get some DOMDocument + DOMXPath() treatment.. i might do it myself one of these days

**Comment by zulus** [comment]
> What about using the stubs available at https://github.com/JetBrains/phpstorm-stubs ?
> Is that repository [license](https://github.com/JetBrains/phpstorm-stubs/blob/master/LICENSE) ok for Eclipse projects (it's Apache License 2.0)?

In theory yes, but these code stubs are „universal” and require parsing via latest php , for example now they use special attributes to introduce differences between php versions, more advanced that phpdoc „@since”. We are not ready for this.

So until I’ll drop wtp/dltk this will require enourmus amount of work.
