### ISSUE TITLE
Oracle OCI types are incorrect

### ISSUE THREAD

**Issue by ghost** [eclipse/pdt#128]
**Describe the bug**
PDT recognises OCI_Collection - which is not a valid OCI type
PDT doesn't recognise OCICollection - which is the valid type

Please can the list of valid Eclipse types be updated to correctly recognise the Oracle OCI types

**Describe the eclipse environment**
2021-12

**Describe your system**
Windows 10 - PHP 8.1

**To Reproduce**
final public static function collectionToArray(OCICollection $OCIcollection) : array {

Eclipse will "zigzag" OCICollection and fail to resolve it to a type. This is incorrect as the script executes perfectly.

On the other hand, Eclipse will recognise OCI_Collection as a valid type. But execution of the script will fail as the type is invalid

**Expected behavior**
Eclipse PDT should recognise the OCICollection type as a valid type.

**Screenshots**
![image](https://user-images.githubusercontent.com/25826774/155229671-052de41d-6918-4321-986e-18c817aed662.png)

**Additional context**

**Comment by agmckee** [comment]
[OCI-Collection](https://web.archive.org/web/20200401094300/https://www.php.net/manual/en/class.OCI-Collection.php) was renamed [OCICollection](https://www.php.net/manual/en/class.ocicollection.php) in PHP 8. PDT doesn't yet formally support PHP 8.
That being said, it looks like there was an error in the naming before given that it should have been OCI-Collection not OCI_Collection, despite the usual PHP conventions.

**Comment by zulus** [comment]
Unfortunately I'm not able to generate correct oci8.php stubs, because this extension not work on M1

I'll try to do this before release

**Comment by mlocati** [comment]
What about using docker?
PS: you can easily install PHP extensions in docker images with my https://github.com/mlocati/docker-php-extension-installer

**Comment by zulus** [comment]
hmm this might be an option. Instant client in theory works with aarch64

**Comment by mlocati** [comment]
Yep, it should work with aarch64 - see https://github.com/mlocati/docker-php-extension-installer/blob/master/install-php-extensions#L1862
