### ISSUE TITLE
Github-Wiki: wrong link to 'PDT main wiki page'

### ISSUE THREAD

**Issue by ungeahnt** [eclipse/pdt#131]
The link to the 'PDT main wiki page' on Github/wiki (https://github.com/eclipse/pdt/wiki) is wrong:

> Currently main wiki page is [http://wiki.eclipse.org/PDT](https://github.com/eclipse/pdt/wiki/wiki.eclipse.org/PDT).

It should be: [http://wiki.eclipse.org/PDT](https://wiki.eclipse.org/PDT)

**Comment by zulus** [comment]
Fixed
