### ISSUE TITLE
tot

### ISSUE THREAD

**Issue by Magdiphp** [eclipse/pdt#144]
**Describe the bug**

**Describe the eclipse environment**
A clear and concise description about Eclipse Version (ex. 2020-03), PDT version (7.0, 7.2) and installed additional plugins (PyDev, Symfony, Doctrine)

**Describe your system**
 - PHP Version (if related)
 - Webserver Version (if related)
 - Utilis (composer, php unit, Xdebug etc...)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by agmckee** [comment]
Dead? Probably
