### ISSUE TITLE
Cannot set PHP exe path

### ISSUE THREAD

**Issue by tobiascapin** [eclipse/pdt#153]
I'm experiencing an error in Eclipes interface while setting PHP exe in Windows environment.

![immagine](https://user-images.githubusercontent.com/3449410/236409977-113c03ac-1123-4a2c-af37-ccc5ebcc44ea.png)

Eclipse version is: 2023-03 (4.27.0)
OS Windows 11 x64
Java: x64 17.0.7

I tried without success to update eclipse, pdt package and java.

**Comment by zulus** [comment]
Could you attach error log?  (Window -> Show View -> Error Log)

**Comment by tobiascapin** [comment]
Sure, here you are:

![immagine](https://user-images.githubusercontent.com/3449410/236470102-62822436-885a-4a2c-a04e-5805c8ea53f9.png)

**Comment by zulus** [comment]
I uploaded new snapshots of DLTK and PDT, should work fine now
