### ISSUE TITLE
CTRL+click (navigate to source) doesn't work on \Attribute:: constants.

### ISSUE THREAD

**Issue by pounard** [eclipse/pdt#155]
CTRL+click (navigate to source) doesn't work on \Attribute:: constants.

![Capture d’écran du 2023-05-16 16-31-23](https://github.com/eclipse/pdt/assets/341855/dc41f7f3-4836-46dc-bb8a-ca4a29378861)

This is always the case, in every context.

 - OS: Linux 6.3.1-arch2-1
 - PDT version: Eclipse IDE for PHP Developers, Build id: 20230309-1520, With PDT 8.0.0.202305142018	
 - PHP Version: 8.0

Navigating to the `\Attribute` class is working fine, and auto-completion of those constants is working fine as well.

**Comment by zulus** [comment]
I was sure that I fixed it yesterday, hmm, assigned

**Comment by zulus** [comment]
Fixed in upcoming build
