### ISSUE TITLE
Autocompletion is not working with statement such as (new Foo())->...

### ISSUE THREAD

**Issue by pounard** [eclipse/pdt#157]
When writing code such as:

```php
(new \DateTime())->for #...
```

Then hit CTRL+space, auto-completion does not work.

Nevertheless, once written:

```php
(new \DateTime())->format('some string')
```

Hitting CTRL+click on the `format` method will work.

This is reproducible with all classes, in all contextes.

This is always the case, in every context.

 - OS: Linux 6.3.1-arch2-1
 - PDT version: Eclipse IDE for PHP Developers, Build id: 20230309-1520, With PDT 8.0.0.202305142018	
 - PHP Version: 8.0

**Comment by zulus** [comment]
I've checked on current master build and woks fine. Please reopen if still see a problem.

I'm using latest DLTK snapshot
