### ISSUE TITLE
Custom build of PDT

### ISSUE THREAD

**Issue by Blount** [eclipse/pdt#167]
I attempt to build a version of PDT containing a modification related to my previous ticket.
I built it with this command : 
`mvn clean install -Prelease -DskipSign -DskipTests`
Now, how I can include it in my Eclipse instance ?
In the log, I read some line : Installing /home/.../pdt/dev/org.eclipse.php-repository/target/p2artifacts.xml to /home/.../.m2/repository/org/eclipse/php/org.eclipse.php.repository/8.0.0-SNAPSHOT/org.eclipse.php.repository-8.0.0-SNAPSHOT-p2artifacts.xml
So, all file are built in "/home/.../.m2" ?

**Comment by zulus** [comment]
In general latest build from master is always here: https://download.eclipse.org/tools/pdt/updates/latest-nightly/ so you can quickly add to you eclipse.

To build local version best command will be: `mvn clean verify -DskipTests`, release is not necessary, just like install in .m2. After build you will find eclipse p2 repository under _PROJECT_DIR_/dev/org.eclipse.php-repository/target/repository, this directory you can add to your eclipse

**Comment by Blount** [comment]
Yes I have already the nightly build in my Eclipse. I want to build a version including a personal patch ;)
I will try your process, thank.

**Comment by Blount** [comment]
Ok all work fine, thank !!
