### ISSUE TITLE
 Autocomplete does not work with backslash 

### ISSUE THREAD

**Issue by edson-nascimento** [eclipse/pdt#55]
**Describe the bug**
When I define the return type in a function in a specific namespace, when calling this function and putting its result in a variable, the autocomplete does not work ex \ PDOStatement this happens for any object.

**Describe the eclipse environment**
 - Eclipse IDE for PHP Developers
 - Version: 2020-03 (4.15.0)
 - Build id: 20200313-1211

**Describe your system**
 - OS: Win 10 home
 - Version 1909
 - PHP Version 7.3.1
 - composer, autoload psr-4, 

**To Reproduce**
![error](https://user-images.githubusercontent.com/12473581/82218005-9bffe300-98f1-11ea-88cd-3fef8e1f829d.PNG)

**Expected behavior**
![ok](https://user-images.githubusercontent.com/12473581/82218009-9d311000-98f1-11ea-9a01-d3c1bb0b4aef.PNG)

**Additional context**
The autocomplete only works if you put "use PDOStatement;"

Any suggestion?
The problem is only in the autocomplete, as my code is running without errors.

**Comment by zulus** [comment]
Thank You for report! 

Change will be visible in tomorrow snapshot. It require both DLTK and WTP nightly so will be better to wait for 2020-06 M3.
