### ISSUE TITLE
PDT Formatter: One-line shell-style comments converted to one-line C++-style comments

### ISSUE THREAD

**Issue by grouillard** [eclipse/pdt#59]
**Describe the bug**
Upon using the code formatter, one-line shell-style comments such as `# This is a one-line shell-style comment` are converted to `// This is a one-line shell-style comment` (one-line C++-style comments).

Since we're using the `#` and `//` comment types for slightly different uses, it is somewhat annoying.

**Describe the eclipse environment**
 - IDE: MyEclipse Enterprise Workbench version 2020.5.18, based on Eclipse Platform version 4.15.0.v20200305-0155.
 - PDT: Eclipse PDT version 7.1.0.202002212050.

**Describe your system**
 - OS: Windows 10
 - Version 1909 (build 18363.836)

**To Reproduce**
1. Open a PHP file having a one-line shell-style comment such as `# This is a one-line shell-style comment`
2. Right-click on the document
3. Click Source > Format
4. The document's one-line shell-style comments are converted to one-line C++-style comments such as `// This is a one-line shell-style comment` 

**Expected behavior**
The comment type should not change. Upon reformatting, the `#` comment token should remain `#`.

**Comment by mlocati** [comment]
If we'll adopt PHP-CS-Fixer, there's a specific configurable fixer for this

**Comment by zulus** [comment]
Interesting, looks like information about comment style is ignored during parsing:

```java
public class Comment extends ASTNode {
        public final static int TYPE_SINGLE_LINE = 0;
	public final static int TYPE_MULTILINE = 1;
	public final static int TYPE_PHPDOC = 2;
        // ...
}
```

**Comment by guyr-evision** [comment]
In plugins/org.eclipse.php.formatter.core/src/org/eclipse/php/formatter/core/CodeFormatterVisitor.java, around [line 1224](https://github.com/eclipse/pdt/blob/c3072f7436947ef8f2108331e26e711135300753/plugins/org.eclipse.php.formatter.core/src/org/eclipse/php/formatter/core/CodeFormatterVisitor.java#L1224):
```java
	int commentTokLen = commentContent.startsWith("#") ? 1 : 2;//$NON-NLS-1$
	commentWords = Arrays.asList(
			MagicMemberUtil.WHITESPACE_SEPERATOR.split(commentContent.substring(commentTokLen).trim()));
	commentWords = removeEmptyString(commentWords);
	commentContent = join(commentWords, " "); //$NON-NLS-1$
	commentContent = commentContent.trim();

	boolean newLineStart = true;
	appendToBuffer("//"); //$NON-NLS-1$
```

The token length is obtained for parsing purposes, but when the formatting takes place, it just appends // to the buffer without consideration for the comment style.

**Comment by zulus** [comment]
Nice! Another hardcoded behaviour in our code ;) This should be configurable. 

I haven't time for M3 because I'm still fighting with #44. Anyway I'm assigning to 7.2. Should be simple to fix/extend.

**Comment by tbl0605** [comment]
I'll have a look into this one, I'll already worked enough on class CodeFormatterVisitor ;)
And yes, the fix is pretty trivial, thank you everybody for your analysis.

**Comment by zulus** [comment]
This will be part of 2020-03 M3 and tomorrow snapshot
