### ISSUE TITLE
Javascript Editor function is gone after upgrade to Eclipse 2020-06

### ISSUE THREAD

**Issue by KlaasBonnema** [eclipse/pdt#71]
Up to Eclipse 2020-03, PDT version 7.1 there was a javascript editor included with the PDT IDE environment.
After upgrade to 2020-06 the javascript editor does not work anymore. Instead you can open a javascript source in the Eclipse general text editor which naturally lacks all the relevant features - syntax highlighting, outline, syntax validation, source formatting.

This is in contradiction with the PDT documentation that says that a javascript editor is included in the package.

In fact a stub of Javascript development tools seems to be installed but it has no content. In 2020-03 you can unfold the item but not in 2020-06.

This problem was reported here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=564496 for JSDT and answered with: Standalone JS Editor is not provided anymore. That is a pretty useless answer if you just experienced that your javascript editor has gone missing. 

The current state of 2020-06 is that I am better off using Notepad++ with just syntax highlighting than using the generic text editor inside Eclipse. I was forced to revert to 2020-03, even with the serious DLTK bug that plagues that version.

I am now at a loss how to get back to a fully functioning javascript editor including syntax highlighting, outline, syntax validation, source formatting in combination with Eclipse PDT.

 - OS: Windows
 - Version 10

**Comment by zulus** [comment]
You can re-add old, slow, unmaintained JSDT anytime. It's still supported but no longer delivered via EPP and/or via marketplace install.

EPP 2020-06 is delivered with WildWebDeveloper that finally correctly support ES2015 and many others things. Unfortunately it require nodejs installed on your system. This issue will be solved in 2020-09, it will be delivered with build-in nodejs, similar to VSCode.

**Comment by zulus** [comment]
I forgot, JSDT support is completely dropped in 8.0

**Comment by KlaasBonnema** [comment]
One correction - an upgrade to 2020-06 does not install WildWebDeveloper. It does in fact install a stub of JSDT so to get to WildWebDeveloper you have to de-install JSDT, manually install WildWebDeveloper in Eclipse and do an external install of node.js.

So many things that are just (incorrectly) assumed to be common knowledge. For instance, what is EPP?

**Comment by zulus** [comment]
Thanks, I'll add WildWebDeveloper to PDT dependencies in 8.0 so should be installed together, even during update. But it's strange because I was added WWD into package root. I have to check that.

EPP project (https://www.eclipse.org/epp/) build packages delivered via downloads.eclipse.org. We as a project, normally deliver only p2 repository (https://download.eclipse.org/tools/pdt/updates/latest/ or https://download.eclipse.org/tools/pdt/updates/7.2/) for them. 

JSDT is generally not maintained since years, and mostly broken. 

WildWebDeveloper works similar to VS code and use LanguageServer protocol in background, but for 2020-06 require nodejs on system (vsc have it built-in), as I mentioned before this problem has been solved.

WildWebDeveloper have support for latest JS and also many other like Angular support: https://github.com/eclipse/wildwebdeveloper

Upcoming PDT will deliver couple features based on this approach, for example built-in Twig/Smarty/Razor support

**Comment by nitind** [comment]
KlaasBonnema wrote:
> One correction - an upgrade to 2020-06 does not install WildWebDeveloper. It does in fact install a stub of JSDT so to get to WildWebDeveloper you have to de-install JSDT, manually install WildWebDeveloper in Eclipse and do an external install of node.js.

You shouldn't have needed to uninstall anything for WildWebDeveloper to work, but in 2020-09, JSDT's UI will be scaled back even further to clarify that it now only contributes a subset of its former functionality. It'll still supply the expected fully customizable syntax coloring and templates for JavaScript within, for example, the HTML Editor--where the new org.eclipse.wst.web_js_support.feature/"Eclipse Web JavaScript Developer Tools" feature is installed, such as in the Enterprise Java package--even as the HTML Editor calls out to Wild Web Developer for its JavaScript content assist and hovers.

**Comment by o-alquimista** [comment]
After upgrading from 2020-06 to 2020-09 I no longer have syntax highlighting for JavaScript files.

**Comment by nitind** [comment]
> After upgrading from 2020-06 to 2020-09 I no longer have syntax highlighting for JavaScript files. I'm not sure where to report this regression. WildWebDeveloper?

If it is installed and you are correctly opening the JavaScript file with the Generic Text Editor, yes.

**Comment by o-alquimista** [comment]
The upgrade changed the default editor to "Text Editor" instead of "Generic Text Editor". I changed it back to the latter and it works now. Thank you.

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 16 de set de 2020 11:56, Nitin Dahyabhai escreveu:
