### ISSUE TITLE
Project explorer not refreshing

### ISSUE THREAD

**Issue by pounard** [eclipse/pdt#72]
Hello ! I'm not certain if this a bug of PDT itself or the Eclipse platform, nevertheless since 2020-03 and then still present in 2020-06 when I move, cut/paste or delete files in the project explorer, it doesn't refresh.

Another side effect is that when I double click on the moved file (which still appears with the old name) it fails in opening it (since the file doesn't exist) but with a unrelated message, and tries to open the system editor instead, which at its turn yells because the file does not exist.

Version is:
```
Eclipse IDE for PHP Developers (includes Incubating components)
Version: 2020-06 (4.16.0)
Build id: 20200615-1200
```

I have quite a few addons installed, but I noticed the bug prior to installing it.

 - OS: Running ArchLinux, uname output: `Linux guinevere 5.7.6-arch1-1 #1 SMP PREEMPT Thu, 25 Jun 2020 00:14:47 +0000 x86_64 GNU/Linux`

1. Add a new PHP project
2. Right click on a PHP file in the explorer, then select "Delete"
3. See that explorer view didn't refresh
4. Double click on the old name still there.

**Comment by zulus** [comment]
I'm unable to reproduce on Mac, this might be platform specific. 

Have you something in logs?

**Comment by pounard** [comment]
Yes, I'm currently setting up a new dev box with a fresh install, I'll try to reproduce it and report back to you. It could be anything such as a broken workspace state (my main working workspace is a few years old and experienced many major Eclipse upgrades) or a GTK-related repaint problem.

**Comment by pounard** [comment]
OK I retried on a fresh install, I couldn't reproduce the bug, I think it's related to the workspace I use on my corporate dev laptop. It actually could be related to SWT since I did forced a few options to change behaviours in both my eclipse.ini file and in the wrapper script I wrote to run Eclipse.

I'm closing this, I guess it's related to misconfiguration.
