### ISSUE TITLE
When you write a root constant using \CONST_NAME (with \ prefix) PDT hangs for a while

### ISSUE THREAD

**Issue by pounard** [eclipse/pdt#78]
Since as far as I know, using this code is fine, and CTRL+Click navigation works:

```php
$foo = SOME_ROOT_CONST;
```

But when I write:

```php
$foo = \SOME_ROOT_CONST;
```

In order to explicit the constant fully qualified name, when I hover using CTRL on the const name, it hangs. It spins for a while, burn down my CPU for a few seconds, then come back to normal, and navigation doesn't work.

Version is:
```
Eclipse IDE for PHP Developers (includes Incubating components)
Version: 2020-06 (4.16.0)
Build id: 20200615-1200
```

I have quite a few addons installed, including PDT Extensions, but I think that it did happens when I hadn't installed any other plugins yet.

 - OS: Running ArchLinux, uname output: `Linux guinevere 5.7.6-arch1-1 #1 SMP PREEMPT Thu, 25 Jun 2020 00:14:47 +0000 x86_64 GNU/Linux`

**Comment by zulus** [comment]
Cause is funny and scary. PDT evaluate constants in horrible way:

In this case AST is not `scalar` but `FullyQualifiedName`. It's correct but PDT selection engine run inferencing for that:

1. If namespaced and type constants looking for TypeName + constant name
2. Otherways, scan all namespaces and look for constant (our cpu hog)
3. If not found try to resolve similar to scalar (just by name).

ConstantDeclarationEvaluator and ConstantDeclarationEvaluator logic have to be changed. I'm not sure if in this case inferencing is really necessary.

**Comment by pounard** [comment]
I never looked at PDT internals, but I trust you for spotting the red flag :)

**Comment by pounard** [comment]
I would add that point 2) is definitely wrong, if constant is not found, it should only lookup in the root namespace instead of attempting to find it in all namespaces on a simple CTRL+hover, looks like it shouldn't, at least, be triggered when simply hovering it ?

**Comment by zulus** [comment]
> It seems that point 2) is very weird, constants are not indexed with they FQDN to start with ? If that was the case, lookup would be instantaneous ?

I created proper indexation long time ago. Mostly for fast function/method search, but I've never noticed about UI freeze for constant since we move to async autocompletion. Moving to Github was right decision ;)

**Comment by pounard** [comment]
> Moving to Github was right decision ;)

Agreed, fun thing thought I'm using PDT since it was initially released (it's a long time ago) and I have an account on eclipse.org, I did comment once a few bugs, a few years back.

I'm glad seeing this project still alive, I love PDT, and use it 8 hours a day, every bug or annoying behaviour that could be fixed is a miracle for me :)

**Comment by pounard** [comment]
I'm reading your changes and commits, and sometime feel guilty making you work, but it helps me slowly understanding how PDT works; maybe one day it'll motivate me to regain my Java level from another life, and try to step up in contributing to PDT. Thanks for everything !

**Comment by zulus** [comment]
PDT still paying cost for incorrect integration with DLTK. Also looks like none believe that PHP ever will gain advance OOP and other features.

Each bug like this gives me reason to reimplement/reinvent broken part :P

> maybe one day it'll motivate me to regain my Java level from another life, and try to step up in contributing to PDT. 

Let's fun ;)

I'll merge it as-is. PDT 8.0 takes longer than I expected (too much private work), and I'm afraid it will be not ready for 2020-09, but for 2020-12 with PHP 8 support.
