### ISSUE TITLE
Broken (404) link to "GitHub project" from homepage

### ISSUE THREAD

**Issue by Chealer** [eclipse/pdt#85]
**Describe the bug**
The first paragraph of the _Contributing_ section in [PDT's homepage](https://www.eclipse.org/pdt/) has a "GitHub project" link which points to https://eclipse.org/eclipse/pdt
That URL yields an HTTP 404 error.

**To Reproduce**
1. Go to PDT's homepage
2. Click on 'GitHub project'

**Comment by zulus** [comment]
Fixed: https://git.eclipse.org/c/www.eclipse.org/pdt.git/commit/?id=2966371d1db75e435dc0897093cdb6c1f2c396a9

Will be visible after cache refresh. Thank You
