### ISSUE TITLE
Eclipse PDT does not check MacOS Java version, before automatic update.

### ISSUE THREAD

**Issue by mitchelldmiller** [eclipse/pdt#91]
**Describe the bug**
Eclipse PDT will not start after automatic update.

**Describe the eclipse environment**
Eclipse PDT 2020-06. Nothing extra installed.

**Describe your system**
 - OS: MacOs
 - Version 10.15.6 (19G2021)
 - java version "1.8.0_05"

**To Reproduce**
1. Wait for automatic update.
2. Click OK - restart Eclipse.
3. Error: `Incompatible JVM: Version 11 or greater is required.`

**Expected behavior**
I expected Eclipse to restart with updates.

**Additional context**
My Mac is using current Java: `Java Update was last run at 11:57 on 9/17/20.`

Fixed by deleting Eclipse, using new Eclipse Installer 2020‑09 R, with Java.

**Comment by zulus** [comment]
As far as I remember this was fixed by Eclipse core project itself
