### ISSUE TITLE
PHP Language Library of PHP 7.3 is used for PHP 7.4 project

### ISSUE THREAD

**Issue by zaltysz** [eclipse/pdt#93]
When project is configured for PHP 7.4, PDT wrongly uses PHP 7.3 Language Library for it. This makes validation fail when functions/classes newly introduced in PHP7.4 are being used, i.e. \WeakReference.

Eclipse 2020-09, PDT 7.2.0.202005271851

I think the culprit is https://github.com/eclipse/pdt/blob/4c8d7f9dfc7842ca40ebfdb7b1b902910344985d/plugins/org.eclipse.php.core/src/org/eclipse/php/internal/core/language/DefaultLanguageModelProvider.java - it has no case for PHP 7.4, and defaults to 7.3.

![Screenshot from 2020-09-22 15-38-54](https://user-images.githubusercontent.com/19934545/93884890-274c1380-fcec-11ea-8b3c-4f345ad8e4ae.png)

**Comment by ibakirov** [comment]
Same on Eclipse Version: 2021-06 (4.20.0) Build id: 20210612-2011. Not only Core.php but all Core API files are with v.7.3.0 version

![eclipse-wrong-php-version](https://user-images.githubusercontent.com/7983476/125607677-f7d0aea3-13ec-4571-a0ed-b4dd2feaf4e6.png)
