### ISSUE TITLE
To support named parameters

### ISSUE THREAD

**Issue by mostafabarmshory** [eclipse/pdt#98]
**Is your feature request related to a problem? Please describe.**
The PHP 8 supports the named parameter. So you can pass parameters with their names. The IDE shows syntax error on named parameters.

**Is this feature require new UI elements or modify existing?**
No. No need to change any UI elements.

**Describe the solution you'd like**
To support named parameter as described in PHP 8 specifications.

**Describe alternatives you've considered**
To use plain text editor.

**Additional context**
See the following links for more information about PHP named parameters.
https://www.php.net/releases/8.0/en.php
https://wiki.php.net/rfc/named_params

**Comment by stanolacko** [comment]
+1 for me

**Comment by rxbracho** [comment]
Still a problem in the Version: **2022-09 (4.25.0)** with Build id: **20220908-1902**

Any idea if/when this will be fixed? I _strongly_ disagree that this is an enhancement, it shows syntax errors on a perfectly valid PHP syntax since 8.0 and they are in 8.2!

Thanks,
Rafael

**Comment by zulus** [comment]
Is part of #148, closing
